// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function init_plant_database(){
enum particle_type{
	CUBED_BELL_RISER,
	FLICKERING
}

enum plant_effects{
	CHANGE_HEAT,
	HARM,
	GREGARIOUSNESS,
	RIPEN_SURROUNDING
}


global.plant_database = ds_map_create();

ds_map_add(global.plant_database, plant_cards.STARDUST,  
		{
        name: "Stardust",
        type: "Flower",
        effect: plant_effects.CHANGE_HEAT,
		effect_strength: 4,
		effect_radius: "3x3",
        description: "A warm, intense glow radiates from these yellow flowers.",
		days_to_grow: 3,
		max_vitality: 7,
		days_until_ripe: -1,
		nutritiousness: 0,
		perennial: false,
		heat_pref: 10,
		heat_tol: 15,
		water_intake: 2,
		nutrient_intake: 1,
		particle: particle_type.FLICKERING,
		glow_sprite: spr_glow_sprite_400x400,
		plant_sprite: [spr_stardust_seedling, spr_stardust_regular, spr_stardust_lavish, spr_stardust_sick, spr_stardust_dead],
        fruit_sprite: spr_fruit_golden_clover,
		fruit_card: fruit_cards.GOLDEN_PEACH,
		fruit_x: 0,
		fruit_y: 0,
		fruit_wiggle: 0,
		glow_points: [
            { x: -100, y: -100 },
            { x: 100, y: -120 },
			{ x: 0, y: -150 },
            { x: -25, y: -40 }
        ],
		glow_size: 0.4,
		glow_strength: 0.15, // values from 0 to 1
		pulse_strength: 0.002, // higher value means larger radius swing
		flicker_factor: 0.05,
		flicker_speed: game_get_speed(gamespeed_fps) / 2 //higher values mean slower flickering
    });

ds_map_add(global.plant_database, plant_cards.MOON_ROOT,
    {
        name: "Moon Root",
        type: "Plant",
        effect: -1,
		effect_strength: 0,
		effect_radius: 0,
        description: "It guides us through the night like a beacon of wisdom.",
		days_until_ripe: 0,
		days_to_grow: 4,
		max_vitality: 7,
		nutritiousness: 2,
		perennial: false,
		heat_pref: 25,
		heat_tol: 10,
		water_intake: 1,
		nutrient_intake: 1,
		particle: particle_type.FLICKERING,
		glow_sprite: spr_glow_blue_seed,
		plant_sprite: [spr_moon_root_seedling, spr_moon_root, spr_moon_root_lavish, spr_moon_root_sick, spr_moon_root_dead],
        fruit_sprite: -1,
		fruit_card: fruit_cards.MOONFRUIT,
		fruit_x: 0, 
		fruit_y: 0,
		fruit_wiggle: 15,
		glow_points: [
            { x: 30, y: 0 }
        ],
		glow_size: 3,
		glow_strength: 0.7,
		pulse_strength: 0.005,
		flicker_factor: 0.02,
		flicker_speed: game_get_speed(gamespeed_fps)
    })
ds_map_add(global.plant_database, plant_cards.GOLDEN_CLOVER,
    {
        name: "Golden Clover",
        type: "Plant - Perennial",
        effect: -1,
		effect_strength: 0,
		effect_radius: 0,
        description: "Yields beautiful and delicious starfruit.",
		days_until_ripe: 2,
		days_to_grow: 3,
		max_vitality: 8,
		nutritiousness: 4,
		perennial: true,
		heat_pref: 24,
		heat_tol: 10,
		water_intake: 2,
		nutrient_intake: 2,
		particle: particle_type.CUBED_BELL_RISER,
		glow_sprite: spr_glow_sprite_400x400,
		plant_sprite: [spr_golden_clover_seedling, spr_golden_clover_regular, spr_golden_clover_lavish, spr_golden_clover_sick, spr_golden_clover_dead],
        fruit_sprite: spr_fruit_golden_clover,
		fruit_card: fruit_cards.GOLDEN_PEACH,
		fruit_x: 40, 
		fruit_y: -25,
		fruit_wiggle: 15,
		glow_points: [{ x: 0, y: -70 }],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    })
ds_map_add(global.plant_database, plant_cards.MAGIKA,
	{
        name: "Magika",
        type: "Plant - Perennial",
        effect: plant_effects.HARM,
		effect_strength: 1,
		effect_radius: 4,
        description: "Yields beautiful and delicious starfruit.",
		days_until_ripe: 7,
		days_to_grow: 4,
		max_vitality: 6,
		nutritiousness: 1,
		perennial: true,
		heat_pref: 10,
		heat_tol: 4,
		water_intake: 1,
		nutrient_intake: 3,
		particle: -1,
		particle: particle_type.FLICKERING,
		glow_sprite: spr_glow_sprite_400x400,
		plant_sprite: [spr_magika_seedling, spr_magika_regular, spr_magika_lavish, spr_magika_sick, spr_magika_dead],
        fruit_sprite: spr_fruit_magika,
		fruit_card: fruit_cards.MAGIFRUIT,
		fruit_x: 25, 
		fruit_y: - 255,
		fruit_wiggle: 15,
		glow_points: [
            { x: 0, y: -120 }
        ],
		glow_size: 0.5,
		glow_strength: 0.3,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    })
ds_map_add(global.plant_database, plant_cards.PUMPKIN,
	{
        name: "Skull of Amun",
        type: "Plant",
        effect: -1,
		effect_strength: 0,
		effect_radius: 0,
        description: "Takes time and a lot of sun to grow, but will feed you for days on end.",
		days_until_ripe: 0,
		days_to_grow: 9,
		max_vitality: 4,
		nutritiousness: 11,
		perennial: false,
		heat_pref: 22,
		heat_tol: 6,
		water_intake: 2,
		nutrient_intake: 2,
		glow_sprite: spr_glow_sprite_400x400,
		plant_sprite: [spr_pumpkin_seedling, spr_pumpkin_regular, spr_pumpkin_lavish, spr_pumpkin_sick, spr_pumpkin_dead],
		fruit_sprite: -1,
		fruit_card: fruit_cards.BLOATKIN,
		fruit_x: x, 
		fruit_y: y,
		fruit_wiggle: 15,
		particle: -1,
        glow_points: [
        ],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    })
ds_map_add(global.plant_database, plant_cards.MILKYWAY,
	{
        name: "Milkyway",
        type: "Fruit",
        effect: plant_effects.CHANGE_HEAT,
		effect_strength: -4,
		effect_radius: "3x3",
		description: "Its spiraling leaves provide a breeze of fresh air, even to surrounding plants.",
		days_until_ripe: 2,
		days_to_grow: 3,
		max_vitality: 5,
		nutritiousness: 1,
		perennial: false,
		heat_pref: 12,
		heat_tol: 12,
		water_intake: 1,
		nutrient_intake: 1,
		glow_sprite: -1,
		plant_sprite: [spr_milkyway_seedling, spr_milkyway_regular, spr_milkyway_lavish, spr_milkyway_sick, spr_milkyway_dead],
		fruit_sprite: -1,
		fruit_card: -1,
		fruit_x: x, 
		fruit_y: y,
		fruit_wiggle: 15,
		particle: -1,
        glow_points: [
        ],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    });
	
ds_map_add(global.plant_database, plant_cards.MANYSOUL_GRAIN,
	{
        name: "Manysoul Grain",
        type: "Weed",
        effect: plant_effects.GREGARIOUSNESS,
		effect_strength: 1,
		effect_radius: "3x3",
		description: "It grows faster and stronger when it is not alone. Just like us.",
		days_until_ripe: 6,
		days_to_grow: 4,
		max_vitality: 5,
		nutritiousness: 5,
		perennial: true,
		heat_pref: 30,
		heat_tol: 10,
		water_intake: 2,
		nutrient_intake: 2,
		glow_sprite: -1,
		plant_sprite: [spr_manysoul_grain_seedling, spr_manysoul_grain_regular, spr_manysoul_grain_lavish, spr_manysoul_grain_sick, spr_manysoul_grain_dead],
		fruit_sprite: spr_fruit_golden_clover,
		fruit_card: fruit_cards.GOLDEN_PEACH,
		fruit_x: x, 
		fruit_y: y-200,
		fruit_wiggle: 15,
		particle: -1,
        glow_points: [
        ],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    });

ds_map_add(global.plant_database, plant_cards.FEASTBULB,
	{
        name: "The Feastbulb",
        type: "Fruitbearer",
        effect: -1,
		effect_strength: 1,
		effect_radius: "3x3",
		description: "When it´s ripe, we dance, we sing and we feast.",
		days_until_ripe: 0,
		days_to_grow: 9,
		max_vitality: 6,
		nutritiousness: 15,
		perennial: false,
		heat_pref: 28,
		heat_tol: 8,
		water_intake: 2,
		nutrient_intake: 2,
		glow_sprite: -1,
		plant_sprite: [spr_feastbulb_seedling, spr_feastbulb_regular, spr_feastbulb_lavish, spr_feastbulb_sick, spr_feastbulb_dead],
		fruit_sprite: spr_fruit_golden_clover,
		fruit_card: fruit_cards.GOLDEN_PEACH,
		fruit_x: x, 
		fruit_y: y-200,
		fruit_wiggle: 15,
		particle: -1,
        glow_points: [
        ],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    });
	
ds_map_add(global.plant_database, plant_cards.HOLLOW_BONSAI,
	{
        name: "Hollow Bonsai",
        type: "Tree",
        effect: -1,
		effect_strength: 1,
		effect_radius: "3x3",
		description: "Its barky deadwood makes for a surprisingly tough material.",
		days_until_ripe: 0,
		days_to_grow: 6,
		max_vitality: 5,
		nutritiousness: 0,
		perennial: false,
		heat_pref: 30,
		heat_tol: 15,
		water_intake: 1,
		nutrient_intake: 1,
		glow_sprite: -1,
		plant_sprite: [spr_hollow_bonsai_seedling, spr_hollow_bonsai_lavish, spr_hollow_bonsai_regular, spr_hollow_bonsai_sick, spr_hollow_bonsai_dead],
		fruit_sprite: -1,
		fruit_card: material.DEADWOOD,
		fruit_x: x, 
		fruit_y: y-200,
		fruit_wiggle: 15,
		particle: -1,
        glow_points: [
        ],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    });
	
ds_map_add(global.plant_database, plant_cards.ASHEN_SHELLWOOD,
	{
        name: "Ashen Shellwood",
        type: "Tree",
        effect: -1,
		effect_strength: 1,
		effect_radius: "3x3",
		description: "It takes time, but delivers plenty of deadwood once grown.",
		days_until_ripe: 3,
		days_to_grow: 8,
		max_vitality: 5,
		nutritiousness: 0,
		perennial: true,
		heat_pref: 34,
		heat_tol: 10,
		water_intake: 1,
		nutrient_intake: 1,
		glow_sprite: -1,
		plant_sprite: [spr_ashen_shellwood_seedling, spr_ashen_shellwood_regular, spr_ashen_shellwood_lavish, spr_ashen_shellwood_sick, spr_ashen_shellwood_dead],
		fruit_sprite: -1,
		fruit_card: material.DEADWOOD,
		fruit_x: x, 
		fruit_y: y-200,
		fruit_wiggle: 15,
		particle: -1,
        glow_points: [
        ],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    });
	
ds_map_add(global.plant_database, plant_cards.PILLAR_OF_THE_EARTH,
	{
        name: "Pillar of the earth",
        type: "Tree",
        effect: plant_effects.RIPEN_SURROUNDING,
		effect_strength: 1,
		effect_radius: "3x3",
		description: "We gather around these natural bulwarks to honor the goddess of the earth.",
		days_until_ripe: 6,
		days_to_grow: 7,
		max_vitality: 10,
		nutritiousness: 0,
		perennial: false,
		heat_pref: 34,
		heat_tol: 10,
		water_intake: 2,
		nutrient_intake: 1,
		glow_sprite: -1,
		plant_sprite: [spr_pillar_of_earth_seedling, spr_pillar_of_earth_regular, spr_pillar_of_earth_lavish, spr_pillar_of_earth_sick, spr_pillar_of_earth_dead],
		fruit_sprite: -1,
		fruit_card: fruit_cards.GOLDEN_PEACH,
		fruit_x: x, 
		fruit_y: y-200,
		particle: -1,
        glow_points: [
        ],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    });

}