// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function init_plant_database(){
enum particle_type{
	CUBED_BELL_RISER,
	FLICKERING
}

enum plant_effects{
	CHANGE_HEAT,
	HARM
}

enum material{
	DEADWOOD,
	RADIANT_ROOT,
	MIRRORGLAS,
	MOONSTONE
}

global.plant_database = ds_map_create();

ds_map_add(global.plant_database, "stardust",   
		{
        name: "Stardust",
        type: "Flower",
        effect: plant_effects.CHANGE_HEAT,
		effect_strength: 4,
		effect_radius: "3x3",
        description: "A warm, intense glow radiates from these yellow flowers.",
		days_to_grow: 3,
		max_vitality: 7,
		days_until_ripe: -1,
		nutritiousness: 0,
		perennial: false,
		heat_pref: 10,
		heat_tol: 15,
		water_pref: 6,
		water_tol: 3,
		water_intake: 2,
		nutrient_intake: 1,
		particle: particle_type.FLICKERING,
		glow_sprite: spr_glow_sprite_400x400,
		plant_sprite: [spr_stardust_seedling, spr_stardust_regular, spr_stardust_lavish, spr_stardust_sick, spr_stardust_dead],
        fruit_sprite: -1,
		fruit_card: -1,
		material_card: material.RADIANT_ROOT,
		fruit_card_n: 0,
		fruit_x: 0,
		fruit_y: 0,
		fruit_wiggle: 0,
		glow_points: [
            { x: -100, y: -100 },
            { x: 100, y: -120 },
			{ x: 0, y: -150 },
            { x: -25, y: -40 }
        ],
		glow_size: 0.4,
		glow_strength: 0.15, // values from 0 to 1
		pulse_strength: 0.002, // higher value means larger radius swing
		flicker_factor: 0.05,
		flicker_speed: game_get_speed(gamespeed_fps) / 2 //higher values mean slower flickering
    });

ds_map_add(global.plant_database, "moon_root",
    {
        id: 1,
        name: "Moon Root",
        type: "Plant",
        effect: -1,
		effect_strength: 0,
		effect_radius: 0,
        description: "It guides us through the night like a beacon of wisdom.",
		days_until_ripe: 0,
		days_to_grow: 4,
		max_vitality: 7,
		nutritiousness: 2,
		perennial: false,
		heat_pref: 5,
		heat_tol: 10,
		water_pref: 7,
		water_tol: 3,
		water_intake: 1,
		nutrient_intake: 1,
		particle: particle_type.FLICKERING,
		glow_sprite: spr_glow_blue_seed,
		plant_sprite: [spr_moon_root_seedling, spr_moon_root, spr_moon_root_lavish, spr_moon_root_sick, spr_moon_root_dead],
        fruit_sprite: -1,
		fruit_card: "moon_fruit",
		fruit_card_n: 1,
		material_card: material.MOONSTONE,
		fruit_x: 0, 
		fruit_y: 0,
		fruit_wiggle: 15,
		glow_points: [
            { x: 30, y: 0 }
        ],
		glow_size: 3,
		glow_strength: 0.7,
		pulse_strength: 0.005,
		flicker_factor: 0.02,
		flicker_speed: game_get_speed(gamespeed_fps)
    })
ds_map_add(global.plant_database, "golden_clover",
    {
        id: 2,
        name: "Golden Clover",
        type: "Plant - Perennial",
        effect: -1,
		effect_strength: 0,
		effect_radius: 0,
        description: "Yields beautiful and delicious starfruit.",
		days_until_ripe: 2,
		days_to_grow: 3,
		max_vitality: 8,
		nutritiousness: 4,
		perennial: true,
		heat_pref: 16,
		heat_tol: 10,
		water_pref: 6,
		water_tol: 3,
		water_intake: 2,
		nutrient_intake: 2,
		particle: particle_type.CUBED_BELL_RISER,
		glow_sprite: spr_glow_sprite_400x400,
		plant_sprite: [spr_golden_clover_seedling, spr_golden_clover_regular, spr_golden_clover_lavish, spr_golden_clover_sick, spr_golden_clover_dead],
        fruit_sprite: spr_fruit_golden_clover,
		fruit_card: "golden_peach",
		fruit_card_n: 1,
		material_card: material.DEADWOOD,
		fruit_x: 40, 
		fruit_y: -25,
		fruit_wiggle: 15,
		glow_points: [{ x: 0, y: -70 }],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    })
ds_map_add(global.plant_database, "magika",
	{
		id: 3,
        name: "Magika",
        type: "Plant - Perennial",
        effect: plant_effects.HARM,
		effect_strength: 1,
		effect_radius: 4,
        description: "Yields beautiful and delicious starfruit.",
		days_until_ripe: 7,
		days_to_grow: 4,
		max_vitality: 6,
		nutritiousness: 1,
		perennial: true,
		heat_pref: 10,
		heat_tol: 4,
		water_pref: 4,
		water_tol: 2,
		water_intake: 1,
		nutrient_intake: 3,
		particle: -1,
		particle: particle_type.FLICKERING,
		glow_sprite: spr_glow_sprite_400x400,
		plant_sprite: [spr_magika_seedling, spr_magika_regular, spr_magika_lavish, spr_magika_sick, spr_magika_dead],
        fruit_sprite: spr_fruit_magika,
		fruit_card: "magifruit",
		fruit_card_n: 1,
		material_card: material.MIRRORGLAS,
		fruit_x: 25, 
		fruit_y: - 255,
		fruit_wiggle: 15,
		glow_points: [
            { x: 0, y: -120 }
        ],
		glow_size: 0.5,
		glow_strength: 0.3,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    })
ds_map_add(global.plant_database, "pumpkin",
	{
		id: 4,
        name: "Skull of Amun",
        type: "Plant",
        effect: -1,
		effect_strength: 0,
		effect_radius: 0,
        description: "Takes time and a lot of sun to grow, but will feed you for days on end.",
		days_until_ripe: 0,
		days_to_grow: 9,
		max_vitality: 4,
		nutritiousness: 11,
		perennial: false,
		heat_pref: 22,
		heat_tol: 6,
		water_pref: 8,
		water_tol: 3,
		water_intake: 2,
		nutrient_intake: 2,
		glow_sprite: spr_glow_sprite_400x400,
		plant_sprite: [spr_pumpkin_seedling, spr_pumpkin_regular, spr_pumpkin_lavish, spr_pumpkin_sick, spr_pumpkin_dead],
		fruit_sprite: -1,
		fruit_card: "bloatkin",
		fruit_card_n: 1,
		material_card: material.RADIANT_ROOT,
		fruit_x: x, 
		fruit_y: y,
		fruit_wiggle: 15,
		particle: -1,
        glow_points: [
        ],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    })
ds_map_add(global.plant_database, "milkyway",
	{
		id: 5,
        name: "Milkyway",
        type: "Fruit",
        effect: plant_effects.CHANGE_HEAT,
		effect_strength: -4,
		effect_radius: "3x3",
		description: "Its spiraling leaves provide a breeze of fresh air, even to surrounding plants.",
		days_until_ripe: 2,
		days_to_grow: 3,
		max_vitality: 5,
		nutritiousness: 1,
		perennial: false,
		heat_pref: 12,
		heat_tol: 12,
		water_pref: 6,
		water_tol: 3,
		water_intake: 1,
		nutrient_intake: 1,
		glow_sprite: -1,
		plant_sprite: [spr_milkyway_seedling, spr_milkyway_regular, spr_milkyway_lavish, spr_milkyway_sick, spr_milkyway_dead],
		fruit_sprite: -1,
		fruit_card: -1,
		fruit_card_n: 1,
		material_card: material.MOONSTONE,
		fruit_x: x, 
		fruit_y: y,
		fruit_wiggle: 15,
		particle: -1,
        glow_points: [
        ],
		glow_size: 1.1,
		glow_strength: 0.2,
		pulse_strength: 0.002,
		flicker_factor: 0,
		flicker_speed: game_get_speed(gamespeed_fps)/4
    });
}